algoritmo "Exercício #02"
// Função : Estruturado
// Autor : Josias Neto
// Data : 18/02/2024
var
   Raio, Area: Real
inicio
   EscrevaL ("---------------------------------------")
   EscrevaL (" CÁLCULO DE ÁREA DE UMA CIRCUNFERÊNCIA ")
   EscrevaL ("---------------------------------------")
   Escreva  ("Digite o Raio: ")
   Leia (Raio)
   Area <- Pi * Raio^2
   EscrevaL ("Área da Circunferência: ", Area:5:2)
   EscrevaL ("---------------------------------------")
fimalgoritmo
