algoritmo "Exercício #01"
// Função : Estruturado
// Autor : Josias Neto
// Data : 18/02/2024
var
   A, B, X: Real
inicio
   EscrevaL ("-------------------------")
   EscrevaL ("     SOMA DE VALORES     ")
   EscrevaL ("-------------------------")
   Escreva  ("Digite o 1º Valor: ")
   Leia (A)
   Escreva  ("Digite o 2º Valor: ")
   Leia (B)
   X <- A + B
   EscrevaL ("-------------------------")
   EscrevaL ("A SOMA DOS VALORES É: ", X)
   Escreva  ("-------------------------")
fimalgoritmo
